apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/man2611/fastapi-redis-helm.git
    targetRevision: HEAD
    path: charts/fastapi-redis
    helm:
      valueFiles:
        - ../values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
